### ISSUE TITLE
I've got a Nord slack theme that works better with Dark mode, would you consider adding it here?

### ISSUE THREAD

**Issue by finsqm** [arcticicestudio/nord-slack#11]
Theme:

#1A1D21,#3B4252,#88C0D0,#2E3440,#3B4252,#D8DEE9,#A3BE8C,#81A1C1,#3B4252,#D8DEE9

Issue with the current one:
The background colour on the sidebar is a shade of grey that clashes with the dark mode background grey.

Changes in this theme:
Only the Column BG has been changed, to the slack dark theme background colour

**Comment by arcticicestudio** [comment]
Hi @finsqm :wave:, thanks for your contribution :+1:

Even if this were better compatible with the style of Slack's new new dark mode, the new column background color `#1A1D21` is not part of [Nord's color palettes][1]. Another case that needs to be noted is that not every user uses the dark mode so `#1A1D21` would collide with the color of the application top bar and basically no longer fits the overall style of Nord.

But the nice part is that every user can simply customize the theme on it own like you already did, in the end these are just some HEX codes pastes into some text fields 😄

[1]: https://www.nordtheme.com/docs/colors-and-palettes

**Comment by shaleh** [comment]
@arcticicestudio your points are valid. But the theme presented in the repo is essentially unusable in dark mode. The lighter color sidebar with the dark main area is unattractive at best. While not everyone uses dark mode it is quite popular.

If you could find a color in the palette that would satisfy you it would be great to have an "official" version.

**Comment by arcticicestudio** [comment]
This theme uses [`nord0`][1] for the sidebar which is the darkest color of the Nord palette. One of the design principles of Nord is that "dark" doesn't mean that is must be somewhere near `#000000` which is one of the most common mistakes of "dark modes". Slack also made this mistake and Apple when they decided to simply invert colors, where I am a little disappointed, contrary to their otherwise high quality work.

I'm a fan of the [Refactoding UI][2] book and the great design knowledge of the authors (creators of the famous ["Tailwaind CSS"][3] project) which is used as inspiration for most Nord design concepts. One example I often refer to is [one of the preview from the book regarding "depth of view" when developing "dark modes"][4]:

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/133967773-b2c0235b-0501-4499-9f8d-e6968652e8d2.png" /></p>

This concept can be seen in this Slack theme too where the sidebar should indeed have a color that is brighter than the window. I can see that is doesn't fit the overall appereance, but this is a problem of Slack itself because they don't allow users to customize the actual window background color when enabling the "dark mode".

The solution for this problem would be that Slack allows to customize the background color for the both the "dark" and "light" mode, but I guess they have way plans with way higher priorities than improving this small disadvantage.
Therefore I can currently only point out that every user has to adapt the theme on their own.

[1]: https://www.nordtheme.com/docs/colors-and-palettes#nord0
[2]: https://www.refactoringui.com
[3]: https://tailwindcss.com
[4]: https://twitter.com/steveschoger/status/1151160261170126850/photo/1
